import { Gig, Review, Order } from "./types";

export const MOCK_GIGS: Gig[] = [
  {
    id: "1",
    userId: "u2",
    title: "I will build a responsive website using React and Tailwind for your project",
    desc: "Hi! I'm a 3rd-year CSE student at CVR with hands-on experience building real-world web apps. I've made portfolio sites, college club pages, and small business websites. I work in React + Tailwind and make sure everything looks great on mobile too. Drop me your requirements and I'll get it done.",
    category: "web-development",
    price: 1499,
    cover: "",
    deliveryTime: 5,
    features: ["Fully Responsive", "React + Tailwind CSS", "Source Code Included", "2 Free Revisions", "WhatsApp Support"],
    totalStars: 22,
    starNumber: 5,
    sales: 12,
    sellerName: "Prachi Pratyusha Acharya",
    sellerPic: "",
  },
  {
    id: "2",
    userId: "u3",
    title: "I will design a professional logo and brand kit for your startup or club",
    desc: "I'm a graphic design enthusiast in my 2nd year. I've designed logos for 3 college fests, a startup, and multiple student clubs. I use Figma and Illustrator. You'll get the logo in all formats — PNG, SVG, and PDF. I care a lot about getting your vision right, so I'll ask questions before I start.",
    category: "graphic-design",
    price: 799,
    cover: "",
    deliveryTime: 3,
    features: ["3 Initial Concepts", "Final Files in All Formats", "Brand Color Palette", "Font Suggestions", "Unlimited Revisions"],
    totalStars: 19,
    starNumber: 4,
    sales: 9,
    sellerName: "Prabhudeb Samal",
    sellerPic: "",
  },
  {
    id: "3",
    userId: "u4",
    title: "I will write SEO blog posts, articles, or college project reports",
    desc: "English Honours student here! I've been writing since school — blogs, reports, essays, you name it. I make sure everything is original (I share the plagiarism report), well-structured, and easy to read. Whether it's a 500-word blog or a 3000-word article, I'll do proper research and deliver on time.",
    category: "content-writing",
    price: 499,
    cover: "",
    deliveryTime: 2,
    features: ["100% Original Content", "Plagiarism Report Included", "SEO Optimized", "Well Researched", "1 Revision"],
    totalStars: 14,
    starNumber: 3,
    sales: 6,
    sellerName: "Subhdendu kumar behera",
    sellerPic: "",
  },
  {
    id: "4",
    userId: "u5",
    title: "I will edit your YouTube videos, Reels, or college project films",
    desc: "Been editing videos for 2+ years — YouTube vlogs, short films, college documentary projects, and social media reels. I use Premiere Pro and After Effects. I'll handle cuts, transitions, colour grading, subtitles, and background music. Send me your raw footage and I'll turn it into something worth watching.",
    category: "video-editing",
    price: 1999,
    cover: "",
    deliveryTime: 4,
    features: ["Colour Grading", "Smooth Transitions", "Subtitles/Captions", "Background Music", "Thumbnail Design"],
    totalStars: 18,
    starNumber: 4,
    sales: 11,
    sellerName: "Ashis ranjan pradhan",
    sellerPic: "",
  },
  {
    id: "5",
    userId: "u6",
    title: "I will tutor you in Maths, Physics, or Chemistry — from basics to board exams",
    desc: "JEE Advanced qualified, currently in 2nd year Engineering. I've helped 20+ juniors clear their backlogs and crack semester exams. I explain concepts simply, solve past papers together, and give short notes you can revise from. Sessions are 1-on-1 via Google Meet and I'm flexible with timings.",
    category: "tutoring",
    price: 299,
    cover: "",
    deliveryTime: 1,
    features: ["1-on-1 Session", "Doubt Clearing", "Handwritten Notes", "Past Paper Practice", "Flexible Timings"],
    totalStars: 25,
    starNumber: 5,
    sales: 22,
    sellerName: "Ankita pattanaik",
    sellerPic: "",
  },
  {
    id: "6",
    userId: "u7",
    title: "I will analyse your data and build dashboards in Python or Excel",
    desc: "Data Science student, done multiple live projects with real datasets. I can clean messy data, find patterns, and build charts or dashboards in Python (matplotlib, seaborn, plotly) or Excel. Great for college mini-projects, internship reports, or business data. I also write a short summary of my findings.",
    category: "data-analysis",
    price: 1199,
    cover: "",
    deliveryTime: 3,
    features: ["Data Cleaning", "Interactive Charts", "Dashboard Design", "Python or Excel", "Summary Report"],
    totalStars: 16,
    starNumber: 4,
    sales: 7,
    sellerName: "Aswhini prakash",
    sellerPic: "",
  },
  {
    id: "7",
    userId: "u8",
    title: "I will build an Android or iOS app prototype using Flutter",
    desc: "Final year student here, interning at a startup. I've shipped 2 Flutter apps on the Play Store. I can build you a clean, working prototype with proper navigation, UI, and basic backend. Perfect for hackathons, college projects, or testing an app idea before spending big.",
    category: "app-development",
    price: 2499,
    cover: "",
    deliveryTime: 7,
    features: ["Flutter (Android + iOS)", "Clean UI", "Working Prototype", "Source Code", "1 Month Support"],
    totalStars: 20,
    starNumber: 4,
    sales: 5,
    sellerName: "Satwik shivum",
    sellerPic: "",
  },
  {
    id: "8",
    userId: "u9",
    title: "I will write and polish your resume, LinkedIn profile, and cover letter",
    desc: "I've helped 30+ students land internships and placements at top companies — TCS, Infosys, startups, you name it. I know what HR looks for. I'll rewrite your resume from scratch or fix the one you have, tailor it to the job you're targeting, and write a cover letter that doesn't sound generic.",
    category: "resume-cv",
    price: 399,
    cover: "",
    deliveryTime: 2,
    features: ["ATS-Friendly Format", "Role-Specific Tailoring", "LinkedIn Optimisation", "Cover Letter Included", "1 Revision"],
    totalStars: 30,
    starNumber: 6,
    sales: 31,
    sellerName: "Priyanshu patra",
    sellerPic: "",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1", gigId: "1", userId: "u10", userName: "Meera K.", userPic: "", star: 5,
    desc: "Prachi built my portfolio site in 4 days and it looks amazing. He kept me updated throughout and fixed a small issue even after delivery. Highly recommend!",
    createdAt: "2026-03-20",
  },
  {
    id: "r2", gigId: "1", userId: "u11", userName: "Rohit D.", userPic: "", star: 4,
    desc: "Good work overall. There was a slight delay but the final output was solid. Communication was good and he explained everything he was building.",
    createdAt: "2026-03-15",
  },
  {
    id: "r3", gigId: "2", userId: "u12", userName: "Kavya M.", userPic: "", star: 5,
    desc: "Priya is so talented. She made 3 different logo concepts and the one I picked was exactly what I had in mind. Super patient with my feedback too.",
    createdAt: "2026-03-18",
  },
  {
    id: "r4", gigId: "3", userId: "u13", userName: "Aditya R.", userPic: "", star: 5,
    desc: "Sneha wrote a 2000-word article for our college magazine and it was genuinely well-researched. Zero plagiarism and submitted on time. Will order again.",
    createdAt: "2026-03-12",
  },
  {
    id: "r5", gigId: "4", userId: "u14", userName: "Neha P.", userPic: "", star: 4,
    desc: "Rahul edited our department farewell video and it came out beautifully. The transitions and music were perfect. One rework was needed but he did it happily.",
    createdAt: "2026-03-10",
  },
  {
    id: "r6", gigId: "5", userId: "u15", userName: "Suresh B.", userPic: "", star: 5,
    desc: "Ananya explained integration in a way no professor ever did. Cleared my backlog concept in one session. Booked 3 more sessions already.",
    createdAt: "2026-03-08",
  },
  {
    id: "r7", gigId: "8", userId: "u16", userName: "Pallavi T.", userPic: "", star: 5,
    desc: "Divya completely rewrote my resume and I got interview calls within a week! She knew exactly what to highlight and what to cut. Worth every rupee.",
    createdAt: "2026-03-22",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "o1", gigId: "1", title: "Responsive React website", price: 1499,
    sellerId: "u2", buyerId: "u1", isCompleted: true,
    createdAt: "2026-03-10", sellerName: "Arjun Patel", buyerName: "You", cover: "",
  },
  {
    id: "o2", gigId: "2", title: "Logo and brand identity design", price: 799,
    sellerId: "u3", buyerId: "u1", isCompleted: false,
    createdAt: "2026-03-22", sellerName: "Priya Sharma", buyerName: "You", cover: "",
  },
];